# Generated by generate-fedora44-kickstart.sh
# Fedora 44, UEFI, minimal XFCE Wayland, explicit package set.
# WARNING: this file contains the LUKS passphrase in clear text.

text
url --url=https://download.fedoraproject.org/pub/fedora/linux/releases/44/Everything/x86_64/os/
repo --name=fedora-updates --baseurl=https://download.fedoraproject.org/pub/fedora/linux/updates/44/Everything/x86_64/ --install
firstboot --disable
eula --agreed
reboot

lang en_GB.UTF-8
keyboard --vckeymap=gb
timezone Europe/London --utc

network --bootproto=dhcp --device=link --activate --hostname=fed-desk --noipv6
firewall --enabled
selinux --enforcing
services --enabled="NetworkManager,firewalld,chronyd,lightdm" --disabled="avahi-daemon,bluetooth,cups"

rootpw --lock
user --name=aslate --groups=wheel --password='$6$vBjuqURNzrddC/HQ$Xqtgns3m4LNscrFJe3vrUT2QafnPUZe50EXd9ZCRCaJltsu/jYSENAEd1v0r7QrODzB6eDzbwKggqDnzy.nDk/' --iscrypted

ignoredisk --only-use=sda
zerombr
clearpart --none
part /boot/efi --fstype=efi --onpart=/dev/sda1 --noformat
part /boot --fstype=ext4 --onpart=/dev/sda3 --noformat
part btrfs.01 --fstype=btrfs --onpart=/dev/sda5 --encrypted --luks-version=luks2 --pbkdf=argon2id --cipher=aes-xts-plain64 --passphrase="my lovely horse"
btrfs none --label=fedora btrfs.01
btrfs / --subvol --name=@ fedora
btrfs /home --subvol --name=@home fedora
btrfs /var --subvol --name=@var fedora
btrfs /tmp --subvol --name=@tmp fedora
btrfs /.snapshots --subvol --name=@snapshots fedora

bootloader --location=boot --append="ipv6.disable=1 rd.luks.options=discard=no"

%packages --excludedocs --inst-langs=en_GB.UTF-8 --nocore
abattis-cantarell-fonts
adwaita-icon-theme
alsa-utils
audit
bash
btrfs-progs
ca-certificates
chrony
coreutils
cryptsetup
dnf5
dosfstools
dracut
dracut-config-rescue
e2fsprogs
efibootmgr
epiphany
fedora-release
fedora-repos
filesystem
firefox
firewalld
glibc-langpack-en
grub2-common
grub2-efi-x64
grub2-efi-x64-modules
grub2-tools
grub2-tools-minimal
kernel
kernel-core
kernel-modules
labwc
less
liberation-fonts-all
lightdm
lightdm-gtk
linux-firmware
lvm2
NetworkManager
NetworkManager-wifi
os-prober
pipewire
pipewire-pulseaudio
policycoreutils
polkit
rpm
selinux-policy-targeted
setup
shadow-utils
shim-x64
sudo
Thunar
tumbler
util-linux
vim-minimal
which
wireplumber
wpa_supplicant
xdg-desktop-portal
xdg-desktop-portal-gtk
xdg-user-dirs
xdg-utils
xfce4-appfinder
xfce4-notifyd
xfce4-panel
xfce4-power-manager
xfce4-screensaver
xfce4-session
xfce4-session-wayland-session
xfce4-settings
xfce4-terminal
xfdesktop
xfwm4
xorg-x11-server-Xwayland
%end

%post --erroronfail --log=/root/kickstart-post.log
set -Eeuo pipefail

# Disable IPv6 persistently in addition to the kernel command line.
cat > /etc/sysctl.d/90-disable-ipv6.conf <<'SYSCTL'
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
SYSCTL

# Disable multicast name resolution and captive-portal probing.
mkdir -p /etc/systemd/resolved.conf.d /etc/NetworkManager/conf.d
cat > /etc/systemd/resolved.conf.d/90-no-multicast.conf <<'RESOLVED'
[Resolve]
LLMNR=no
MulticastDNS=no
RESOLVED
cat > /etc/NetworkManager/conf.d/90-no-connectivity.conf <<'NM'
[connectivity]
enabled=false
NM

systemctl mask avahi-daemon.service avahi-daemon.socket brltty.service brltty-udev.service 2>/dev/null || true
systemctl disable bluetooth.service cups.service brltty.service brltty-udev.service 2>/dev/null || true

# Mask systemd user services for AT-SPI bus and registry
mkdir -p /etc/systemd/user
ln -sf /dev/null /etc/systemd/user/at-spi-dbus-bus.service
ln -sf /dev/null /etc/systemd/user/at-spi2-registryd.service
systemctl --global mask at-spi-dbus-bus.service at-spi2-registryd.service 2>/dev/null || true

# Disable and mask PipeWire and WirePlumber user services globally
ln -sf /dev/null /etc/systemd/user/pipewire.service
ln -sf /dev/null /etc/systemd/user/pipewire.socket
ln -sf /dev/null /etc/systemd/user/pipewire-pulse.service
ln -sf /dev/null /etc/systemd/user/pipewire-pulse.socket
ln -sf /dev/null /etc/systemd/user/wireplumber.service
systemctl --global disable pipewire.service pipewire.socket pipewire-pulse.service pipewire-pulse.socket wireplumber.service 2>/dev/null || true
systemctl --global mask pipewire.service pipewire.socket pipewire-pulse.service pipewire-pulse.socket wireplumber.service 2>/dev/null || true

# Mask DBus auto-activation for AT-SPI accessibility bus
mkdir -p /etc/dbus-1/services
ln -sf /dev/null /etc/dbus-1/services/org.a11y.Bus.service 2>/dev/null || true
ln -sf /dev/null /etc/dbus-1/services/org.a11y.atspi.Registry.service 2>/dev/null || true

# Disable GTK, Qt, and AT-SPI accessibility bridge globally
cat << 'EOF' > /etc/profile.d/disable-accessibility.sh
export NO_AT_BRIDGE=1
export QT_ACCESSIBILITY=0
export GTK_A11Y=none
EOF
chmod +x /etc/profile.d/disable-accessibility.sh

# Lockdown Firewalld: Set default zone to 'drop' with zero exposed services or ports
mkdir -p /etc/firewalld/zones
if [ -f /etc/firewalld/firewalld.conf ]; then
    sed -i 's/^DefaultZone=.*/DefaultZone=drop/' /etc/firewalld/firewalld.conf
else
    cat << 'EOF' > /etc/firewalld/firewalld.conf
DefaultZone=drop
CleanupOnExit=yes
Lockdown=no
EOF
fi

cat << 'EOF' > /etc/firewalld/zones/drop.xml
<?xml version="1.0" encoding="utf-8"?>
<zone target="DROP">
  <short>Drop</short>
  <description>Strict lockdown zone. All incoming traffic is dropped silently with zero exposed services or ports.</description>
</zone>
EOF

cat << 'EOF' > /etc/firewalld/zones/public.xml
<?xml version="1.0" encoding="utf-8"?>
<zone target="DROP">
  <short>Public</short>
  <description>Strict lockdown zone. All incoming traffic is dropped silently with zero exposed services or ports.</description>
</zone>
EOF

# Prefer the XFCE Wayland session in LightDM where the greeter supports it.
mkdir -p /var/lib/AccountsService/users
cat > /var/lib/AccountsService/users/aslate <<'ACCOUNT'
[User]
Session=xfce-wayland
SystemAccount=false
ACCOUNT
chmod 600 /var/lib/AccountsService/users/aslate

# Enable OS probing for other installed operating systems.
if grep -q '^GRUB_DISABLE_OS_PROBER=' /etc/default/grub; then
    sed -i 's/^GRUB_DISABLE_OS_PROBER=.*/GRUB_DISABLE_OS_PROBER=false/' /etc/default/grub
else
    printf '\nGRUB_DISABLE_OS_PROBER=false\n' >> /etc/default/grub
fi
if command -v grub2-mkconfig >/dev/null; then
    grub2-mkconfig -o /etc/grub2-efi.cfg || grub2-mkconfig -o /boot/grub2/grub.cfg || true
fi

# Preserve an audit copy of the explicit package request.
cat > /root/requested-packages.txt <<'PKGS'
# Fedora 44 minimal XFCE Wayland package manifest.
# One package per line. Blank lines and lines beginning with # are ignored.
# Edit this file before running the installer to add or remove packages.
# The generator can verify every listed package against the selected ISO or
# network repositories before it writes the Kickstart file.

# Base system
filesystem
setup
bash
coreutils
util-linux
shadow-utils
sudo
rpm
dnf5
fedora-release
fedora-repos
ca-certificates
glibc-langpack-en
less
vim-minimal
which

# Kernel, initramfs, firmware and storage
kernel
kernel-core
kernel-modules
linux-firmware
dracut
dracut-config-rescue
cryptsetup
btrfs-progs
e2fsprogs
dosfstools
lvm2

# UEFI boot
shim-x64
grub2-efi-x64
grub2-efi-x64-modules
grub2-common
grub2-tools
grub2-tools-minimal
efibootmgr
os-prober

# Security and system services
selinux-policy-targeted
policycoreutils
audit
firewalld
chrony
NetworkManager
NetworkManager-wifi
wpa_supplicant
polkit

# Minimal XFCE Wayland session
lightdm
lightdm-gtk
xfce4-session
xfce4-session-wayland-session
labwc
xfce4-panel
xfdesktop
xfce4-settings
xfce4-terminal
xfce4-appfinder
xfce4-notifyd
xfce4-power-manager
xfce4-screensaver
xfwm4
Thunar
tumbler

# Wayland desktop integration and audio
xdg-user-dirs
xdg-utils
xdg-desktop-portal
xdg-desktop-portal-gtk
pipewire
pipewire-pulseaudio
wireplumber
alsa-utils

# Browsers
firefox
epiphany

# Fonts and basic desktop usability
adwaita-icon-theme
abattis-cantarell-fonts
liberation-fonts-all

# Optional XWayland compatibility. Remove this line for a Wayland-only system.
xorg-x11-server-Xwayland
PKGS
%end
